import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from '../../public/images/profile/sdbrainnobg.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/icons';
import HireMe from '@/components/HireMe';
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg';
import Intro from '@/components/Intro';
import ProfileImage from '@/components/ProfileImage';

export default function Home() {
  return (
    <>
      <Head>
        <title>Protfolio Site</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div
            className='flex justify-center 
              md:m-0
              items-center
              lg:flex-col-reverse
              h-[30rem] lg:h-[60rem]
              lg:space-y-8 space-y-0 lg:space-x-0 space-x-8
            '
          >
            <div className='w-1/2'>
              <Intro />
            </div>
            <div className='w-1/2 md:w-full min-w-8'>
              <ProfileImage />
            </div>
          </div>
          <div className='flex justify-between items-center w-full lg:flex-col'>
            <div className='w-1/2 md:w-full '>
              <Image
                src={profilePic}
                alt='laxman mistry'
                className='w-full h-auto lg:hidden md:inline-block md:w-full '
                priority
                sizes='(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw, 50vw
                '
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText
                text='Turning Vision Into Reality, With Code And Design.'
                className='!text-6xl !text-left pb-1 dark:text-light 
                xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl
                '
              />

              <p className='my-4 text-base font-medium dark:text-light md:text-sm sm:text-xs'>
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link
                  target={'_blank'}
                  href='/dummy.pdf'
                  className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-yellow-500
                dark:bg-light dark:text-dark  hover:dark:bg-dark hover:dark:text-light
              hover:dark:border-yellow-500
              md:p-2 md:px-4 md:text-base
              '
                  // download={true}
                >
                  Resume
                  <LinkArrow className={' w-5 ml-1'} />
                </Link>
                <Link
                  target={'_blank'}
                  href='/mailto:mistrylaxmand@gmail.com'
                  className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base'
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden'>
          <Image
            src={lightBulb}
            alt='Codebucks'
            className='w-full h-auto'
            loading='lazy'
          />
        </div>
      </main>
    </>
  );
}
